### ISSUE TITLE
Does not correctly move cursor when at the bottom of scroll buffer

### ISSUE THREAD

**Issue by cspotcode** [Sebazzz/PSMenu#1]
When the console is at the bottom of its scroll buffer, `CursorTop` remains constant as you write additional lines of output.  Therefore, calling `SetCursorPosition(0, $CursorPosition)` does not actually move the cursor up.

To reproduce this behavior in a console:

```
# Scroll to the bottom of the buffer
write-host ("`n" * 9999)
write-host "`n" ; $before = [Console]::CursorTop ; Write-Host "`n`n`n`n`n`n`n" ; $after = [Console]::CursorTop
write-host $before $after # numbers are the same, or at the very least, do not differ by the correct number of lines
```

I think the logic will need to be updated as follows:

1. When writing the menu, count the number of output lines.
2. `SetCursorPosition(0, [Console]::CursorTop - $NumberOfLinesWritten)`

**Comment by cspotcode** [comment]
I added a pull request fixing this bug.

**Comment by chrisseroka** [comment]
Please create pull request to original repository so that I can update version in powershellgallery

**Comment by cspotcode** [comment]
@chrisseroka @Sebazzz In the gallery I see both PSMenu, corresponding to this repository, and ps-menu, corresponding to chrisseroka/ps-menu.

Why are 2 copies published to the Gallery?  What are the differences?  Can they be consolidated?

**Comment by Sebazzz** [comment]
@cspotcode This repo is a fork and partial rewrite and significant clean-up of the original `ps-menu`. It uses a build system ready for tests, has extensive documentation, some added features, and the cmdlets and module name follow Powershell naming conventions. 

As it is completely incompatible, and the original project appeared to be deserted (last commit 2017), I decided to fork it.
