### ISSUE TITLE
Feature request, ClearOnExit

### ISSUE THREAD

**Issue by shd013** [Sebazzz/PSMenu#14]
Hi, 

I use a psmenu inside a Psreadline keyhandler to show a menu of code snippets. 
I wonder if you have some good idea how to clear the menu "on exit"?
Maybe it could be a feature like a switch argument that clears the menu on exit.

My psreadline macro inserts code at the prompt that sometimes spans more then one row... and the leftovers from the menu garbles inserted command-line. See screenshots below.

![image](https://user-images.githubusercontent.com/15821682/197745775-28b1a187-9de7-4b56-9b30-7cfa6b101b91.png)

![image](https://user-images.githubusercontent.com/15821682/197745858-213aaa8d-fb48-4b8c-9eed-13e23ba00a89.png)

Thanks in advance.

**Comment by Sebazzz** [comment]
I have never tried using it in a PSReadline keyhandler. How is the usage? Have you tried `Clear-Host` or `Write-Host ""` for the number of menu items?

**Comment by Sebazzz** [comment]
Closed due to inactivity
