### ISSUE TITLE
Entering what to do after a selected option

### ISSUE THREAD

**Issue by tcboeira** [Sebazzz/PSMenu#15]
Hello Friend, Good Night

Sorry for the words. I don't speak your language and I'm using a translator

First of all, I also apologize if it seems like some kind of abuse. I've read a lot, I've tested, I've taken the readings again, but I really can't get out of place. And I don't know where my mistake would be.

I am trying to build a menu, from a list I get and eventually it can grow. It is basically the following:

name, domain
DOM1,dom1.com
DOM2,dom2.com
DOM3,dom3.com

As I said, it can eventually grow and that's why the menu font is dynamic.
I think this part is even peaceful.

To simulate this:
`Show-Menu @("option 1", "option 2", "option 3")
`
I tentatively did this:
`Show-Menu @(($test = Import-Csv .\dom-teste.csv).name)
`
And that helps me a lot.

But for me to consider the "door open", I would need to understand how, automatically, and where evidently, for example if someone selects DOM1, shows dom1.com... Or
DOM3, show dom3.com...

To be truly honest, this would be extraordinarily what it would take to develop the solution I envision.

I read the [link ](https://github.com/Sebazzz/PSMenu#custom-options) "https://github.com/Sebazzz/PSMenu#custom-options" but I got the impression that there is no way to build it automatically. I would have to manually inform all the options and what to do in each one of them.

Does anyone have an idea how to help me out of this situation?

Thank you all and have a good week

**Comment by Sebazzz** [comment]
I'm not sure what you mean, but isn't this what you are looking for?

![image](https://user-images.githubusercontent.com/1426097/234378078-4270fa8e-df3f-42e4-8254-c95a252655fb.png)

You now get the fully object back can do with it whatever you want.

**Comment by Sebazzz** [comment]
Closed due to inactivity
