### ISSUE TITLE
Host supported

### ISSUE THREAD

**Issue by seawerst** [Sebazzz/PSMenu#17]
Is there a reason you are limiting the supported host to ConsoleHost in [Test-HostSupported.ps1](https://github.com/Sebazzz/PSMenu/blob/master/PSMenu/Private/Test-HostSupported.ps1) ?
I'm using VS Code to develop and this library seems to work well with it as a host.

`$Host.Name` is reported as "Visual Studio Code Host"

**Comment by Sebazzz** [comment]
Yes @seawerst, because feature detection is not really possible, so I've added a whitelist of allowed hosts. I suppose we can add VSCode now - this used to not work.

**Comment by seawerst** [comment]
@Sebazzz Here is a PR: #18

**Comment by Sebazzz** [comment]
Thanks, released in v0.2.0
