### ISSUE TITLE
Does not export the `Get-MenuSeparator` function

### ISSUE THREAD

**Issue by cspotcode** [Sebazzz/PSMenu#3]
https://github.com/Sebazzz/PSMenu/blob/master/PSMenu/PSMenu.psd1#L77

**Comment by Sebazzz** [comment]
Yes, that is a documentation issue. Does not matter in actual use.

**Comment by cspotcode** [comment]
On my machine, it did not import that function until I added it to the manifest.  It was required.

**Comment by cspotcode** [comment]
Ah, now I see that v0.1.0 doesn't match `master`, and the build script is responsible for updating the manifest accordingly before publication.

https://github.com/Sebazzz/PSMenu/compare/v0.1.0..master#diff-9dca8688c1287069f38e3081a8585ffcL77

So this works correctly when installed via PowerShell gallery, but if you checkout git master and `ipmo ./PSMenu/PSMenu.psd1` you will not be able to use the `Get-MenuSeparator` function.

**Comment by Sebazzz** [comment]
No, you need to build first. The published version indeed not have the issue. 

I'Il check whether I pushed the latest.
